import comp from "C:/Users/muysengly/Desktop/My Github/blog/src/.vuepress/.temp/pages/docs/course_001/018.html.vue"
const data = JSON.parse("{\"path\":\"/docs/course_001/018.html\",\"title\":\"18. Exceptions Handling\",\"lang\":\"en-US\",\"frontmatter\":{\"title\":\"18. Exceptions Handling\",\"description\":\"Python provides...\",\"lead\":\"\",\"date\":\"2022-01-25T13:41:39.000Z\",\"lastmod\":\"2022-01-25T13:41:39.000Z\",\"draft\":false,\"images\":[],\"type\":\"docs\",\"toc\":true,\"weight\":18,\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/docs/course_001/018.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"My Website\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"18. Exceptions Handling\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Python provides...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"en-US\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-11-20T04:45:30.000Z\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2022-01-25T13:41:39.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-11-20T04:45:30.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"18. Exceptions Handling\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2022-01-25T13:41:39.000Z\\\",\\\"dateModified\\\":\\\"2024-11-20T04:45:30.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Sengly MUY\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"Assertions in Python\",\"slug\":\"assertions-in-python\",\"link\":\"#assertions-in-python\",\"children\":[]},{\"level\":3,\"title\":\"The assert Statement\",\"slug\":\"the-assert-statement\",\"link\":\"#the-assert-statement\",\"children\":[]},{\"level\":3,\"title\":\"Example\",\"slug\":\"example\",\"link\":\"#example\",\"children\":[]},{\"level\":2,\"title\":\"What is Exception?\",\"slug\":\"what-is-exception\",\"link\":\"#what-is-exception\",\"children\":[]},{\"level\":2,\"title\":\"Handling an exception\",\"slug\":\"handling-an-exception\",\"link\":\"#handling-an-exception\",\"children\":[{\"level\":3,\"title\":\"Syntax\",\"slug\":\"syntax\",\"link\":\"#syntax\",\"children\":[]},{\"level\":3,\"title\":\"Example\",\"slug\":\"example-1\",\"link\":\"#example-1\",\"children\":[]},{\"level\":3,\"title\":\"Example\",\"slug\":\"example-2\",\"link\":\"#example-2\",\"children\":[]}]},{\"level\":2,\"title\":\"The except Clause with No Exceptions\",\"slug\":\"the-except-clause-with-no-exceptions\",\"link\":\"#the-except-clause-with-no-exceptions\",\"children\":[]},{\"level\":2,\"title\":\"The except Clause with Multiple Exceptions\",\"slug\":\"the-except-clause-with-multiple-exceptions\",\"link\":\"#the-except-clause-with-multiple-exceptions\",\"children\":[]},{\"level\":2,\"title\":\"The try-finally Clause\",\"slug\":\"the-try-finally-clause\",\"link\":\"#the-try-finally-clause\",\"children\":[{\"level\":3,\"title\":\"Example\",\"slug\":\"example-3\",\"link\":\"#example-3\",\"children\":[]}]},{\"level\":2,\"title\":\"Argument of an Exception\",\"slug\":\"argument-of-an-exception\",\"link\":\"#argument-of-an-exception\",\"children\":[{\"level\":3,\"title\":\"Example\",\"slug\":\"example-4\",\"link\":\"#example-4\",\"children\":[]}]},{\"level\":2,\"title\":\"Raising an Exceptions\",\"slug\":\"raising-an-exceptions\",\"link\":\"#raising-an-exceptions\",\"children\":[{\"level\":3,\"title\":\"Syntax\",\"slug\":\"syntax-1\",\"link\":\"#syntax-1\",\"children\":[]},{\"level\":3,\"title\":\"Example\",\"slug\":\"example-5\",\"link\":\"#example-5\",\"children\":[]}]},{\"level\":2,\"title\":\"User-Defined Exceptions\",\"slug\":\"user-defined-exceptions\",\"link\":\"#user-defined-exceptions\",\"children\":[]}],\"git\":{\"createdTime\":1732077930000,\"updatedTime\":1732077930000,\"contributors\":[{\"name\":\"MUY SENGLY\",\"email\":\"muysengly@gmail.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":7.17,\"words\":2150},\"filePathRelative\":\"docs/course_001/018.md\",\"localizedDate\":\"January 25, 2022\",\"excerpt\":\"<p>Python provides two very important features to handle any unexpected error in your Python programs and to add debugging capabilities in them −</p>\\n<ul>\\n<li><strong>Exception Handling</strong> − This would be covered in this tutorial. Here is a list standard Exceptions available in Python: <a href=\\\"https://www.tutorialspoint.com/python/standard_exceptions.htm\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Standard Exceptions</a>.</li>\\n<li><strong>Assertions</strong> − This would be covered in <a href=\\\"https://www.tutorialspoint.com/python/assertions_in_python.htm\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Assertions in Python</a> tutorial.</li>\\n</ul>\"}")
export { comp, data }
